kind: "ReplicationController"
apiVersion: "v1"
metadata:
    name: "mongo-connector"
spec:
    replicas: 1
    selector:
      type: "mongo-connector"
    template:
      metadata:
        labels:
          type: "mongo-connector"
      spec:
        containers:
          - name: "mongo-connector"
            image: "teknologist/docker-mongo-connector:latest"
            env:
                - name: MONGO
                  value: "mongo-cluster.default.cluster.local"
                - name: ELASTICSEARCH
                  value: "elasticsearch.default.cluster.local"
            command: ["/bin/bash","/tmp/startup.sh"]
            volumeMounts:
                - name: mongo-connector-persistent-storage
                  mountPath: /data
        volumes:
        - name: mongo-connector-persistent-storage
          nfs:
              server: 192.168.176.230
              path: "/volume1/kube-nfs/mongo-connector"
